(function() {var implementors = {};
implementors["node_archive"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"node_archive/struct.Cached.html\" title=\"struct node_archive::Cached\">Cached</a>",synthetic:false,types:["node_archive::tarball::Cached"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"node_archive/struct.Remote.html\" title=\"struct node_archive::Remote\">Remote</a>",synthetic:false,types:["node_archive::tarball::Remote"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"node_archive/zip/struct.Cached.html\" title=\"struct node_archive::zip::Cached\">Cached</a>",synthetic:false,types:["node_archive::zip::Cached"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"node_archive/zip/struct.Remote.html\" title=\"struct node_archive::zip::Remote\">Remote</a>",synthetic:false,types:["node_archive::zip::Remote"]},];
implementors["progress_read"] = [{text:"impl&lt;R:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a>, T, F:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.FnMut.html\" title=\"trait core::ops::function::FnMut\">FnMut</a>(<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.reference.html\">&amp;</a>T, <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.usize.html\">usize</a>) -&gt; T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/io/trait.Read.html\" title=\"trait std::io::Read\">Read</a> for <a class=\"struct\" href=\"progress_read/struct.ProgressRead.html\" title=\"struct progress_read::ProgressRead\">ProgressRead</a>&lt;R, T, F&gt;",synthetic:false,types:["progress_read::ProgressRead"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
